const currencyWordNames: Record<string, string> = {
  dollar: 'USD',
  dollars: 'USD',
  euro: 'EUR',
  euros: 'EUR',
  pound: 'GBP',
  pounds: 'GBP',
  rouble: 'RUB',
  roubles: 'RUB',
  ruble: 'RUB',
  rubles: 'RUB',
  yen: 'JPY',
  yuan: 'CNY',
  rupee: 'INR',
  rupees: 'INR',
  real: 'BRL',
  reais: 'BRL',
  peso: 'MXN',
  pesos: 'MXN',
}

export const SUPPORTED_CURRENCY_CODES = [
  'USD',
  'EUR',
  'GBP',
  'CAD',
  'RUB',
  'JPY',
  'CNY',
  'CHF',
  'AUD',
  'KRW',
  'INR',
  'BRL',
  'MXN',
  'PLN',
  'SEK',
  'NOK',
  'DKK',
  'CZK',
  'HUF',
  'TRY',
  'NZD',
  'SGD',
  'HKD',
  'ZAR',
  'THB',
  'UAH',
  'ILS',
] as const

export const currencySymbols: Record<string, string> = {
  '$': 'USD',
  '€': 'EUR',
  '£': 'GBP',
  '¥': 'JPY',
  '₽': 'RUB',
  '₴': 'UAH',
  '₩': 'KRW',
  '₹': 'INR',
  'R$': 'BRL',
}

export { currencyWordNames }

export const weightContextPattern
  = /\b(?:lb|lbs|kg|gram|grams|ounce|ounces|tonne|tonnes|stone|stones|centner|centners|carat|carats)\b/i

export const knownUnitTokens = new Set([
  ...SUPPORTED_CURRENCY_CODES.map(code => code.toLowerCase()),
  'meter',
  'meters',
  'm',
  'cm',
  'mm',
  'km',
  'inch',
  'inches',
  'foot',
  'feet',
  'ft',
  'yard',
  'yards',
  'mile',
  'miles',
  'gram',
  'grams',
  'kg',
  'lb',
  'lbs',
  'pound',
  'pounds',
  'centner',
  'centners',
  'tonne',
  'tonnes',
  'stone',
  'stones',
  'carat',
  'carats',
  'ounce',
  'ounces',
  'second',
  'seconds',
  'minute',
  'minutes',
  'hour',
  'hours',
  'day',
  'days',
  'week',
  'weeks',
  'month',
  'months',
  'year',
  'years',
  'celsius',
  'fahrenheit',
  'kelvin',
  'bit',
  'byte',
  'kb',
  'mb',
  'gb',
  'tb',
  'liter',
  'liters',
  'litre',
  'litres',
  'gallon',
  'gallons',
  'pint',
  'pints',
  'quart',
  'quarts',
  'cup',
  'cups',
  'teaspoon',
  'teaspoons',
  'tablespoon',
  'tablespoons',
  'mil',
  'rod',
  'rods',
  'chain',
  'chains',
  'hectare',
  'hectares',
  'are',
  'ares',
  'acre',
  'acres',
  'point',
  'points',
  'line',
  'lines',
  'hand',
  'hands',
  'furlong',
  'furlongs',
  'cable',
  'cables',
  'nauticalmile',
  'nauticalmiles',
  'league',
  'leagues',
  'radian',
  'radians',
  'degree',
  'degrees',
  'mcsecond',
  'mcminute',
  'mchour',
  'mcday',
  'mcweek',
  'mcmonth',
  'mcyear',
  'px',
  'pixel',
  'pixels',
  'pt',
  'em',
  'mph',
  'kmh',
  'knot',
  'knots',
  'kn',
  'hz',
  'khz',
  'mhz',
  'ghz',
  'thz',
  'joule',
  'joules',
  'calorie',
  'calories',
  'cal',
  'kcal',
  'watt',
  'watts',
  'kilowatt',
  'kilowatts',
  'horsepower',
  'hp',
  'fathom',
  'fathoms',
  'ftm',
  'lightyear',
  'lightyears',
  'ly',
  'microgram',
  'micrograms',
  'mcg',
  'bushel',
  'bushels',
  'bsh',
  'frame',
  'frames',
  'fps',
  ...Object.keys(currencyWordNames),
])

export const lengthInchesByUnit: Record<string, number> = {
  inch: 1,
  inches: 1,
  cm: 1 / 2.54,
  mm: 1 / 25.4,
  m: 39.37007874015748,
  meter: 39.37007874015748,
  meters: 39.37007874015748,
  km: 39370.07874015748,
  foot: 12,
  feet: 12,
  ft: 12,
  yard: 36,
  yards: 36,
  mile: 63360,
  miles: 63360,
}

export const timeZoneAliases: Record<string, string> = {
  'pst': 'America/Los_Angeles',
  'pdt': 'America/Los_Angeles',
  'est': 'America/New_York',
  'edt': 'America/New_York',
  'cst': 'America/Chicago',
  'cdt': 'America/Chicago',
  'mst': 'America/Denver',
  'mdt': 'America/Denver',
  'hkt': 'Asia/Hong_Kong',
  'jst': 'Asia/Tokyo',
  'ist': 'Asia/Kolkata',
  'gmt': 'Etc/GMT',
  'utc': 'UTC',
  'cet': 'Europe/Paris',
  'cest': 'Europe/Paris',
  'aest': 'Australia/Sydney',
  'aedt': 'Australia/Sydney',
  'nzst': 'Pacific/Auckland',
  'nzdt': 'Pacific/Auckland',
  'kst': 'Asia/Seoul',

  // Airport codes
  'lax': 'America/Los_Angeles',
  'sfo': 'America/Los_Angeles',
  'jfk': 'America/New_York',
  'ewr': 'America/New_York',
  'ord': 'America/Chicago',
  'lhr': 'Europe/London',
  'cdg': 'Europe/Paris',
  'fra': 'Europe/Berlin',
  'nrt': 'Asia/Tokyo',
  'hnd': 'Asia/Tokyo',
  'icn': 'Asia/Seoul',
  'pek': 'Asia/Shanghai',
  'hkg': 'Asia/Hong_Kong',
  'sin': 'Asia/Singapore',
  'bkk': 'Asia/Bangkok',
  'del': 'Asia/Kolkata',
  'dxb': 'Asia/Dubai',
  'syd': 'Australia/Sydney',
  'akl': 'Pacific/Auckland',
  'gru': 'America/Sao_Paulo',
  'svo': 'Europe/Moscow',

  // City aliases (not in IANA)
  'seattle': 'America/Los_Angeles',
  'san francisco': 'America/Los_Angeles',
  'las vegas': 'America/Los_Angeles',
  'boston': 'America/New_York',
  'miami': 'America/New_York',
  'washington': 'America/New_York',
  'dallas': 'America/Chicago',
  'houston': 'America/Chicago',
  'barcelona': 'Europe/Madrid',
  'milan': 'Europe/Rome',
  'munich': 'Europe/Berlin',
  'beijing': 'Asia/Shanghai',
  'mumbai': 'Asia/Kolkata',
  'dubai': 'Asia/Dubai',
  'melbourne': 'Australia/Melbourne',

  // Country names
  'japan': 'Asia/Tokyo',
  'china': 'Asia/Shanghai',
  'korea': 'Asia/Seoul',
  'india': 'Asia/Kolkata',
  'thailand': 'Asia/Bangkok',
  'singapore': 'Asia/Singapore',
  'australia': 'Australia/Sydney',
  'france': 'Europe/Paris',
  'germany': 'Europe/Berlin',
  'spain': 'Europe/Madrid',
  'italy': 'Europe/Rome',
  'uk': 'Europe/London',
  'russia': 'Europe/Moscow',
  'brazil': 'America/Sao_Paulo',
  'mexico': 'America/Mexico_City',
  'canada': 'America/Toronto',
  'turkey': 'Europe/Istanbul',
  'israel': 'Asia/Jerusalem',
  'uae': 'Asia/Dubai',
  'usa': 'America/New_York',
  'ireland': 'Europe/Dublin',
  'switzerland': 'Europe/Zurich',
  'netherlands': 'Europe/Amsterdam',
  'sweden': 'Europe/Stockholm',
  'norway': 'Europe/Oslo',
  'denmark': 'Europe/Copenhagen',
  'finland': 'Europe/Helsinki',
  'poland': 'Europe/Warsaw',
  'portugal': 'Europe/Lisbon',
  'greece': 'Europe/Athens',
  'ukraine': 'Europe/Kyiv',
}

export const DEFAULT_EM_IN_PX = 16
export const DEFAULT_PPI = 96
export const MATH_UNARY_FUNCTIONS = [
  'sqrt',
  'cbrt',
  'abs',
  'ln',
  'fact',
  'round',
  'ceil',
  'floor',
  'sin',
  'cos',
  'tan',
  'arcsin',
  'arccos',
  'arctan',
  'sinh',
  'cosh',
  'tanh',
  'asinh',
  'acosh',
  'atanh',
  'sind',
  'cosd',
  'tand',
  'asind',
  'acosd',
  'atand',
] as const

export const TIME_UNIT_TOKEN_MAP: Record<string, string> = {
  second: 'mcsecond',
  seconds: 'mcsecond',
  minute: 'mcminute',
  minutes: 'mcminute',
  hour: 'mchour',
  hours: 'mchour',
  day: 'mcday',
  days: 'mcday',
  week: 'mcweek',
  weeks: 'mcweek',
  month: 'mcmonth',
  months: 'mcmonth',
  year: 'mcyear',
  years: 'mcyear',
}

export const HUMANIZED_UNIT_NAMES: Record<
  string,
  { singular: string, plural: string }
> = {
  mcsecond: { singular: 'second', plural: 'seconds' },
  mcminute: { singular: 'minute', plural: 'minutes' },
  mchour: { singular: 'hour', plural: 'hours' },
  mcday: { singular: 'day', plural: 'days' },
  mcweek: { singular: 'week', plural: 'weeks' },
  mcmonth: { singular: 'month', plural: 'months' },
  mcyear: { singular: 'year', plural: 'years' },
  nauticalmile: { singular: 'nautical mile', plural: 'nautical miles' },
  centner: { singular: 'centner', plural: 'centners' },
  point: { singular: 'point', plural: 'points' },
  line: { singular: 'line', plural: 'lines' },
  hand: { singular: 'hand', plural: 'hands' },
  furlong: { singular: 'furlong', plural: 'furlongs' },
  cable: { singular: 'cable', plural: 'cables' },
  league: { singular: 'league', plural: 'leagues' },
  are: { singular: 'are', plural: 'ares' },
  carat: { singular: 'carat', plural: 'carats' },
  mph: { singular: 'mph', plural: 'mph' },
  kmh: { singular: 'km/h', plural: 'km/h' },
  knot: { singular: 'knot', plural: 'knots' },
  calorie: { singular: 'calorie', plural: 'calories' },
  kilocalorie: { singular: 'kilocalorie', plural: 'kilocalories' },
  fathom: { singular: 'fathom', plural: 'fathoms' },
  lightyear: { singular: 'light year', plural: 'light years' },
  microgram: { singular: 'microgram', plural: 'micrograms' },
  bushel: { singular: 'bushel', plural: 'bushels' },
  frame: { singular: 'frame', plural: 'frames' },
}

export const MONTH_NAME_TO_INDEX: Record<string, number> = {
  jan: 1,
  january: 1,
  feb: 2,
  february: 2,
  mar: 3,
  march: 3,
  apr: 4,
  april: 4,
  may: 5,
  jun: 6,
  june: 6,
  jul: 7,
  july: 7,
  aug: 8,
  august: 8,
  sep: 9,
  sept: 9,
  september: 9,
  oct: 10,
  october: 10,
  nov: 11,
  november: 11,
  dec: 12,
  december: 12,
}
