// Ordered native picker metadata; duplicate GLSL labels intentionally share an ID.
export const codeLanguages = [
  { name: 'ABAP', value: 'abap' },
  { name: 'ABC', value: 'abc' },
  { name: 'ActionScript', value: 'actionscript' },
  { name: 'ADA', value: 'ada' },
  { name: 'Alda', value: 'alda' },
  { name: 'Apache Conf', value: 'apache_conf' },
  { name: 'Apex', value: 'apex' },
  { name: 'Apple Script', value: 'applescript' },
  { name: 'AsciiDoc', value: 'asciidoc' },
  { name: 'ASL', value: 'asl' },
  { name: 'ASP vb.NET (VBScript)', value: 'asp_vb_net' },
  { name: 'Assembly x86', value: 'assembly_x86' },
  { name: 'AutoHotkey / AutoIt', value: 'autohotkey' },
  { name: 'Bash', value: 'sh' },
  { name: 'BatchFile', value: 'batchfile' },
  { name: 'Bicep', value: 'bicep' },
  { name: 'C and C++', value: 'c_cpp' },
  { name: 'C#', value: 'csharp' },
  { name: 'Cirru', value: 'cirru' },
  { name: 'Clojure', value: 'clojure' },
  { name: 'Cobol', value: 'cobol' },
  { name: 'CoffeeScript', value: 'coffee' },
  { name: 'ColdFusion', value: 'coldfusion' },
  { name: 'Crystal', value: 'crystal' },
  { name: 'Csound', value: 'csound_orchestra' },
  { name: 'Csound Document', value: 'csound_document' },
  { name: 'Csound Score', value: 'csound_score' },
  { name: 'CSS', value: 'css' },
  { name: 'Curly', value: 'curly' },
  { name: 'D', value: 'd' },
  { name: 'Dart', value: 'dart' },
  { name: 'Diff', value: 'diff' },
  { name: 'Django', value: 'django' },
  { name: 'Dockerfile', value: 'dockerfile' },
  { name: 'Dot', value: 'dot' },
  { name: 'Drools', value: 'drools' },
  { name: 'Edifact', value: 'edifact' },
  { name: 'Eiffel', value: 'eiffel' },
  { name: 'EJS', value: 'ejs' },
  { name: 'Elixir', value: 'elixir' },
  { name: 'Elm', value: 'elm' },
  { name: 'Erlang', value: 'erlang' },
  { name: 'Forth', value: 'forth' },
  { name: 'Fortran', value: 'fortran' },
  { name: 'F#', value: 'fsharp' },
  { name: 'Gcode', value: 'gcode' },
  { name: 'Gherkin', value: 'gherkin' },
  { name: 'Gitignore', value: 'gitignore' },
  { name: 'Glsl', value: 'glsl' },
  { name: 'Go', value: 'golang' },
  { name: 'GraphQL', value: 'graphqlschema' },
  { name: 'Groovy', value: 'groovy' },
  { name: 'HAML', value: 'haml' },
  { name: 'Handlebars', value: 'handlebars' },
  { name: 'Haskell Cabal', value: 'haskell_cabal' },
  { name: 'Haskell', value: 'haskell' },
  { name: 'haXe', value: 'haxe' },
  { name: 'Hjson', value: 'hjson' },
  { name: 'HTML (Elixir)', value: 'html_elixir' },
  { name: 'HTML (Ruby)', value: 'html_ruby' },
  { name: 'HTML', value: 'html' },
  { name: 'INI', value: 'ini' },
  { name: 'Io', value: 'io' },
  { name: 'Java', value: 'java' },
  { name: 'JavaScript', value: 'javascript' },
  { name: 'JSON', value: 'json' },
  { name: 'JSON5', value: 'json5' },
  { name: 'JSONiq', value: 'jsoniq' },
  { name: 'JSP', value: 'jsp' },
  { name: 'JSX', value: 'jsx' },
  { name: 'Julia', value: 'julia' },
  { name: 'Kotlin', value: 'kotlin' },
  { name: 'Kusto (KQL)', value: 'kusto' },
  { name: 'LaTeX', value: 'latex' },
  { name: 'Latte', value: 'latte' },
  { name: 'LESS', value: 'less' },
  { name: 'Liquid', value: 'liquid' },
  { name: 'Lisp', value: 'lisp' },
  { name: 'LiveScript', value: 'livescript' },
  { name: 'LSL', value: 'lsl' },
  { name: 'Lua', value: 'lua' },
  { name: 'Makefile', value: 'makefile' },
  { name: 'Markdown', value: 'markdown' },
  { name: 'Mask', value: 'mask' },
  { name: 'MATLAB', value: 'matlab' },
  { name: 'MediaWiki', value: 'mediawiki' },
  { name: 'MEL', value: 'mel' },
  { name: 'Mikrotik', value: 'mikrotik' },
  { name: 'MIPS', value: 'mips' },
  { name: 'MySQL', value: 'mysql' },
  { name: 'Nginx', value: 'nginx' },
  { name: 'Nim', value: 'nim' },
  { name: 'Nix', value: 'nix' },
  { name: 'Nushell', value: 'nu' },
  { name: 'NSIS', value: 'nsis' },
  { name: 'Nunjucks', value: 'nunjucks' },
  { name: 'Objective-C', value: 'objectivec' },
  { name: 'OCaml', value: 'ocaml' },
  { name: 'OpenEdge ABL', value: 'oeabl' },
  { name: 'OpenGL', value: 'glsl' },
  { name: 'Pascal', value: 'pascal' },
  { name: 'Perl', value: 'perl' },
  { name: 'pgSQL', value: 'pgsql' },
  { name: 'PHP (Blade Template)', value: 'php_laravel_blade' },
  { name: 'PHP', value: 'php' },
  { name: 'Pig', value: 'pig' },
  { name: 'Plain Text', value: 'plain_text' },
  { name: 'Powershell', value: 'powershell' },
  { name: 'Power Query', value: 'powerquery' },
  { name: 'Praat', value: 'praat' },
  { name: 'Prisma', value: 'prisma' },
  { name: 'Prolog', value: 'prolog' },
  { name: 'Properties', value: 'properties' },
  { name: 'Protobuf', value: 'protobuf' },
  { name: 'Pug', value: 'pug' },
  { name: 'Puppet', value: 'puppet' },
  { name: 'Python', value: 'python' },
  { name: 'QML', value: 'qml' },
  { name: 'R', value: 'r' },
  { name: 'Raku', value: 'raku' },
  { name: 'Razor', value: 'razor' },
  { name: 'Red', value: 'red' },
  { name: 'RegExp', value: 'regexp' },
  { name: 'RST', value: 'rst' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'Rust', value: 'rust' },
  { name: 'SAS', value: 'sas' },
  { name: 'SASS', value: 'sass' },
  { name: 'SCAD', value: 'scad' },
  { name: 'Scala', value: 'scala' },
  { name: 'Scheme', value: 'scheme' },
  { name: 'sCrypt', value: 'scrypt' },
  { name: 'SCSS', value: 'scss' },
  { name: 'SJS', value: 'sjs' },
  { name: 'Slim', value: 'slim' },
  { name: 'Smalltalk', value: 'smalltalk' },
  { name: 'Smarty', value: 'smarty' },
  { name: 'Smithy', value: 'smithy' },
  { name: 'Solidity', value: 'solidity' },
  { name: 'Soy Template', value: 'soy_template' },
  { name: 'SQL', value: 'sql' },
  { name: 'SQLServer', value: 'sqlserver' },
  { name: 'Structured Text (IEC 61131-3)', value: 'st' },
  { name: 'Stylus', value: 'stylus' },
  { name: 'SVG', value: 'svg' },
  { name: 'Swift', value: 'swift' },
  { name: 'Tcl', value: 'tcl' },
  { name: 'Terraform', value: 'terraform' },
  { name: 'Tex', value: 'tex' },
  { name: 'Textile', value: 'textile' },
  { name: 'TOML', value: 'toml' },
  { name: 'TSX', value: 'tsx' },
  { name: 'Twig', value: 'twig' },
  { name: 'TypeScript', value: 'typescript' },
  { name: 'Vala', value: 'vala' },
  { name: 'Velocity', value: 'velocity' },
  { name: 'Verilog', value: 'verilog' },
  { name: 'VHDL', value: 'vhdl' },
  { name: 'Visualforce', value: 'visualforce' },
  { name: 'Vue', value: 'vue' },
  { name: 'Wollok', value: 'wollok' },
  { name: 'XML', value: 'xml' },
  { name: 'XSL', value: 'xsl' },
  { name: 'XQuery', value: 'xquery' },
  { name: 'YAML', value: 'yaml' },
  { name: 'Zeek', value: 'zeek' },
] as const

export type CodeLanguageId = (typeof codeLanguages)[number]['value']
export const codeLanguageIds = [
  ...new Set(codeLanguages.map(language => language.value)),
] as [CodeLanguageId, ...CodeLanguageId[]]

const aliases: Record<string, CodeLanguageId> = {
  'js': 'javascript',
  'ts': 'typescript',
  'c': 'c_cpp',
  'cpp': 'c_cpp',
  'c++': 'c_cpp',
  'cs': 'csharp',
  'fs': 'fsharp',
  'shell': 'sh',
  'md': 'markdown',
  'yml': 'yaml',
  'text': 'plain_text',
  'plaintext': 'plain_text',
  'restructuredtext': 'rst',
  'jade': 'pug',
}
const names = new Map<string, CodeLanguageId>(
  codeLanguages.flatMap(({ name, value }) => [
    [name.toLowerCase(), value],
    [value, value],
  ]),
)

export function normalizeCodeLanguage(value: unknown): unknown {
  if (typeof value !== 'string')
    return value
  const key = value.trim().toLowerCase()
  return names.get(key) ?? (Object.hasOwn(aliases, key) ? aliases[key] : key)
}
