import { EditorView } from '@codemirror/view'

export const internalLinksTheme = EditorView.baseTheme({
  '.cm-internal-link': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.24rem',
    padding: '0.02rem 0.3rem',
    borderRadius: '8px',
    border: '1px solid var(--internal-link-border)',
    backgroundColor: 'var(--internal-link-bg)',
    color: 'var(--internal-link-fg)',
    cursor: 'pointer',
    verticalAlign: 'baseline',
    lineHeight: '1.1',
    fontSize: '0.92em',
    position: 'relative',
    top: '1px',
    transition:
      'background-color 120ms ease, border-color 120ms ease, color 120ms ease',
  },
  '.cm-internal-link:hover': {
    border: '1px solid var(--internal-link-border-hover)',
    backgroundColor: 'var(--internal-link-bg-hover)',
    color: 'var(--internal-link-fg-hover)',
  },
  '.cm-internal-link.is-pending': {
    opacity: '0.8',
  },
  '.cm-internal-link.is-broken': {
    opacity: '0.6',
    textDecoration: 'line-through',
  },
  '.cm-internal-link__icon': {
    flexShrink: '0',
    width: '11px',
    height: '11px',
    position: 'relative',
  },
  '.cm-internal-link__label': {
    lineHeight: '1.05',
  },
  '.cm-internal-link-picker': {
    position: 'fixed',
    zIndex: '1000',
    minWidth: '280px',
    maxWidth: '360px',
    borderRadius: '12px',
    border: '1px solid var(--border)',
    backgroundColor: 'var(--background)',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.16)',
    overflow: 'hidden',
  },
  '.cm-internal-link-picker__input': {
    width: '100%',
    padding: '0.75rem 0.9rem',
    border: 'none',
    outline: 'none',
    borderBottom: '1px solid var(--border)',
    backgroundColor: 'transparent',
    color: 'var(--foreground)',
  },
  '.cm-internal-link-picker__results': {
    maxHeight: '280px',
    overflowY: 'auto',
    padding: '0.35rem',
  },
  '.cm-internal-link-picker__group-title': {
    padding: '0.45rem 0.55rem 0.25rem',
    fontSize: '0.7rem',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: 'var(--muted-foreground)',
  },
  '.cm-internal-link-picker__item': {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '0.2rem',
    padding: '0.55rem',
    borderRadius: '10px',
    textAlign: 'left',
    color: 'var(--foreground)',
  },
  '.cm-internal-link-picker__item.is-active': {
    backgroundColor: 'var(--accent)',
    color: 'var(--accent-foreground)',
  },
  '.cm-internal-link-picker__title-row': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
  },
  '.cm-internal-link-picker__location': {
    fontSize: '0.75rem',
    color: 'var(--muted-foreground)',
  },
  '.cm-internal-link-picker__empty': {
    padding: '0.75rem',
    color: 'var(--muted-foreground)',
  },
  '.cm-internal-link-preview': {
    position: 'fixed',
    zIndex: '1000',
    width: 'min(420px, calc(100vw - 24px))',
    maxHeight: '200px',
    overflow: 'auto',
    borderRadius: '12px',
    border: '1px solid var(--border)',
    backgroundColor: 'var(--background)',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.18)',
    padding: '0.9rem',
  },
  '.cm-internal-link-preview__title': {
    fontWeight: '600',
    marginBottom: '0.55rem',
  },
  '.cm-internal-link-preview__body': {
    whiteSpace: 'pre-wrap',
    fontFamily: 'var(--notes-code-font, var(--font-mono))',
    fontSize: '0.85rem',
    lineHeight: '1.45',
  },
})
