export const surfaceClass = 'rounded-lg border border-border bg-card p-4'
export const cardTitleClass = 'mb-3 text-sm font-semibold'
export const demoStackClass = 'space-y-3'

export const options = ['alpha', 'beta', 'gamma'] as const

export const copy = {
  title: 'shadcn2 demo',
  description:
    'Сравнение root UI-адаптеров, legacy shadcn и нового набора shadcn2 перед заменой импортов в приложении.',
  sections: {
    rootUi: 'Root UI adapters',
    rootUiDescription:
      'Совместимые обёртки, которые сохраняют текущий API приложения, но уже опираются на shadcn2.',
    legacyShadcn: 'Legacy shadcn',
    legacyShadcnDescription:
      'Текущие компоненты на базе Radix, которые пока используются в приложении.',
    newShadcn2: 'shadcn2',
    newShadcn2Description:
      'CLI-сгенерированные компоненты на базе Reka, приведённые к масштабу 28px и переведённые на shadcn color tokens.',
  },
  cards: {
    buttons: 'Buttons',
    inputs: 'Inputs',
    text: 'Text',
    textDescription:
      'Реальные UI-паттерны приложения, построенные на UiText вместо инлайн Tailwind-классов.',
    textPatterns: 'UI Patterns',
    textReference: 'Reference',
    contentEditable: 'Contenteditable textarea',
    selection: 'Select and tabs',
    toggles: 'Checkbox and switch',
    checkbox: 'Checkbox',
    switch: 'Switch',
    overlays: 'Tooltip, popover and dialog',
    command: 'Command',
    contextMenu: 'Context menu',
    resizable: 'Resizable panels',
  },
  states: {
    default: 'Default',
    primary: 'Primary',
    danger: 'Destructive',
    secondary: 'Secondary',
    outline: 'Outline',
    ghostButton: 'Ghost',
    disabled: 'Disabled',
    active: 'Active',
    iconText: 'Icon + text',
    ghost: 'Ghost',
  },
  text: {
    inputPlaceholder: 'Введите значение',
    textareaPlaceholder: 'Введите несколько строк',
    contentEditablePlaceholder: 'Редактируемый блок описания',
    description: 'Вспомогательный текст под полем',
    error: 'Что-то пошло не так',
    selectPlaceholder: 'Выберите вариант',
    tabPreview: 'Preview',
    tabCode: 'Code',
    previewBody: 'Область предпросмотра',
    codeBody: 'Область кода',
    tooltipTrigger: 'Показать tooltip',
    tooltip: 'Пример tooltip',
    openPopover: 'Открыть popover',
    openDialog: 'Открыть dialog',
    popoverBody:
      'Содержимое popover уже использует shadcn tokens и компактные отступы.',
    dialogTitle: 'Превью dialog',
    dialogDescription:
      'Используйте этот route, чтобы сравнить пропорции перед заменой импортов в боевых экранах.',
    commandPlaceholder: 'Поиск компонентов...',
    commandEmpty: 'Ничего не найдено.',
    commandGroup: 'Actions',
    rename: 'Rename',
    duplicate: 'Duplicate',
    delete: 'Delete',
    textDefault: 'Default text',
    textMuted: 'Muted text',
    textMono: 'Monospace sample',
    textUppercase: 'Uppercase label',
    textCaption: 'Caption size',
    textSemibold: 'Semibold emphasis',
    // Text demo — real UI patterns
    sidebarTitle: 'My Workspace',
    sidebarSection: 'Folders',
    sidebarFolder1: 'JavaScript',
    sidebarFolder2: 'TypeScript',
    sidebarFolder3: 'Vue Components',
    snippetTitle: 'Array.from() with mapping',
    snippetFolder: 'JavaScript',
    snippetDate: '2 hours ago',
    sectionHeader: 'Request Headers',
    statusLang: 'TypeScript',
    statusPosition: 'Ln 42, Col 18',
    statusEncoding: 'UTF-8',
    emptyState: 'No snippets found',
    emptyStateHint: 'Create a new snippet or change the filter',
    settingLabel: 'Auto-save',
    settingDescription: 'Automatically save snippets after editing',
    codeSize: '2.4 KB',
    codeLines: '84 lines',
    codeLang: 'typescript',
    methodGet: 'GET',
    methodPost: 'POST',
    methodDelete: 'DELETE',
    methodGetPath: '/api/snippets',
    methodPostPath: '/api/snippets',
    methodDeletePath: '/api/snippets/:id',
    rightClick: 'Кликните правой кнопкой по триггеру, чтобы открыть меню.',
    menuTrigger: 'Open menu',
    resizablePanel: 'Panel',
    option: {
      alpha: 'Alpha',
      beta: 'Beta',
      gamma: 'Gamma',
    },
  },
}
