const currencyWordNames: Record<string, string> = {
  dollar: 'USD',
  dollars: 'USD',
  euro: 'EUR',
  euros: 'EUR',
  pound: 'GBP',
  pounds: 'GBP',
  rouble: 'RUB',
  roubles: 'RUB',
  ruble: 'RUB',
  rubles: 'RUB',
  yen: 'JPY',
  yuan: 'CNY',
  rupee: 'INR',
  rupees: 'INR',
  real: 'BRL',
  reais: 'BRL',
  peso: 'MXN',
  pesos: 'MXN',
}

export const DEFAULT_CURRENCY_RATES: Record<string, number> = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  CAD: 1.36,
  RUB: 89.5,
  JPY: 149.5,
  CNY: 7.24,
  CHF: 0.88,
  AUD: 1.53,
  KRW: 1320,
  INR: 83.1,
  BRL: 4.97,
  MXN: 17.15,
  PLN: 4.02,
  SEK: 10.42,
  NOK: 10.55,
  DKK: 6.87,
  CZK: 22.7,
  HUF: 355,
  TRY: 30.2,
  NZD: 1.63,
  SGD: 1.34,
  HKD: 7.82,
  ZAR: 18.6,
  THB: 35.2,
  UAH: 37.5,
  ILS: 3.65,
}

export const currencySymbols: Record<string, string> = {
  '$': 'USD',
  '€': 'EUR',
  '£': 'GBP',
  '¥': 'JPY',
  '₽': 'RUB',
  '₴': 'UAH',
  '₩': 'KRW',
  '₹': 'INR',
  'R$': 'BRL',
}

export { currencyWordNames }

export const weightContextPattern
  = /\b(?:lb|lbs|kg|gram|grams|ounce|ounces|tonne|tonnes|stone|stones|centner|centners|carat|carats)\b/i

export const knownUnitTokens = new Set([
  'usd',
  'eur',
  'gbp',
  'cad',
  'rub',
  'jpy',
  'cny',
  'chf',
  'aud',
  'krw',
  'inr',
  'brl',
  'mxn',
  'pln',
  'sek',
  'nok',
  'dkk',
  'czk',
  'huf',
  'try',
  'nzd',
  'sgd',
  'hkd',
  'zar',
  'thb',
  'uah',
  'ils',
  'meter',
  'meters',
  'm',
  'cm',
  'mm',
  'km',
  'inch',
  'inches',
  'foot',
  'feet',
  'ft',
  'yard',
  'yards',
  'mile',
  'miles',
  'gram',
  'grams',
  'kg',
  'lb',
  'lbs',
  'pound',
  'pounds',
  'centner',
  'centners',
  'tonne',
  'tonnes',
  'stone',
  'stones',
  'carat',
  'carats',
  'ounce',
  'ounces',
  'second',
  'seconds',
  'minute',
  'minutes',
  'hour',
  'hours',
  'day',
  'days',
  'week',
  'weeks',
  'month',
  'months',
  'year',
  'years',
  'celsius',
  'fahrenheit',
  'kelvin',
  'bit',
  'byte',
  'kb',
  'mb',
  'gb',
  'tb',
  'liter',
  'liters',
  'litre',
  'litres',
  'gallon',
  'gallons',
  'pint',
  'pints',
  'quart',
  'quarts',
  'cup',
  'cups',
  'teaspoon',
  'teaspoons',
  'tablespoon',
  'tablespoons',
  'mil',
  'rod',
  'rods',
  'chain',
  'chains',
  'hectare',
  'hectares',
  'are',
  'ares',
  'acre',
  'acres',
  'point',
  'points',
  'line',
  'lines',
  'hand',
  'hands',
  'furlong',
  'furlongs',
  'cable',
  'cables',
  'nauticalmile',
  'nauticalmiles',
  'league',
  'leagues',
  'radian',
  'radians',
  'degree',
  'degrees',
  'numisecond',
  'numiminute',
  'numihour',
  'numiday',
  'numiweek',
  'numimonth',
  'numiyear',
  'px',
  'pixel',
  'pixels',
  'pt',
  'point',
  'points',
  'em',
  ...Object.keys(currencyWordNames),
])

export const lengthInchesByUnit: Record<string, number> = {
  inch: 1,
  inches: 1,
  cm: 1 / 2.54,
  mm: 1 / 25.4,
  m: 39.37007874015748,
  meter: 39.37007874015748,
  meters: 39.37007874015748,
  km: 39370.07874015748,
  foot: 12,
  feet: 12,
  ft: 12,
  yard: 36,
  yards: 36,
  mile: 63360,
  miles: 63360,
}

export const timeZoneAliases: Record<string, string> = {
  pst: 'America/Los_Angeles',
  pdt: 'America/Los_Angeles',
  est: 'America/New_York',
  edt: 'America/New_York',
  cst: 'America/Chicago',
  cdt: 'America/Chicago',
  mst: 'America/Denver',
  mdt: 'America/Denver',
  hkt: 'Asia/Hong_Kong',
  jst: 'Asia/Tokyo',
  ist: 'Asia/Kolkata',
  gmt: 'Etc/GMT',
  utc: 'UTC',
  cet: 'Europe/Paris',
  cest: 'Europe/Paris',
}

export const DEFAULT_EM_IN_PX = 16
export const DEFAULT_PPI = 96
export const NUMI_UNARY_FUNCTIONS = [
  'sqrt',
  'cbrt',
  'abs',
  'ln',
  'fact',
  'round',
  'ceil',
  'floor',
  'sin',
  'cos',
  'tan',
  'arcsin',
  'arccos',
  'arctan',
  'sinh',
  'cosh',
  'tanh',
] as const

export const NUMI_TIME_UNIT_TOKEN_MAP: Record<string, string> = {
  second: 'numisecond',
  seconds: 'numisecond',
  minute: 'numiminute',
  minutes: 'numiminute',
  hour: 'numihour',
  hours: 'numihour',
  day: 'numiday',
  days: 'numiday',
  week: 'numiweek',
  weeks: 'numiweek',
  month: 'numimonth',
  months: 'numimonth',
  year: 'numiyear',
  years: 'numiyear',
}

export const HUMANIZED_UNIT_NAMES: Record<
  string,
  { singular: string, plural: string }
> = {
  numisecond: { singular: 'second', plural: 'seconds' },
  numiminute: { singular: 'minute', plural: 'minutes' },
  numihour: { singular: 'hour', plural: 'hours' },
  numiday: { singular: 'day', plural: 'days' },
  numiweek: { singular: 'week', plural: 'weeks' },
  numimonth: { singular: 'month', plural: 'months' },
  numiyear: { singular: 'year', plural: 'years' },
  nauticalmile: { singular: 'nautical mile', plural: 'nautical miles' },
  centner: { singular: 'centner', plural: 'centners' },
  point: { singular: 'point', plural: 'points' },
  line: { singular: 'line', plural: 'lines' },
  hand: { singular: 'hand', plural: 'hands' },
  furlong: { singular: 'furlong', plural: 'furlongs' },
  cable: { singular: 'cable', plural: 'cables' },
  league: { singular: 'league', plural: 'leagues' },
  are: { singular: 'are', plural: 'ares' },
  carat: { singular: 'carat', plural: 'carats' },
}

export const MONTH_NAME_TO_INDEX: Record<string, number> = {
  jan: 1,
  january: 1,
  feb: 2,
  february: 2,
  mar: 3,
  march: 3,
  apr: 4,
  april: 4,
  may: 5,
  jun: 6,
  june: 6,
  jul: 7,
  july: 7,
  aug: 8,
  august: 8,
  sep: 9,
  sept: 9,
  september: 9,
  oct: 10,
  october: 10,
  nov: 11,
  november: 11,
  dec: 12,
  december: 12,
}
